### ISSUE TITLE
Error code 43 with AMD RX570 on Xcp-NG

### ISSUE THREAD

**Issue by Ansa89** [gnif/vendor-reset#7] opened 2020-11-22 16:44 UTC
Since I started using this module, the graphic card (AMD RX570) stopped working inside the VM with the "error code 43".
Prior to this, I was able to use the same card (with the same configuration) inside the VM, except for the well known reset issue.

This is the log from `dmesg` on the host:
```
pciback 0000:01:00.0: AMD_POLARIS10: version 1.1
pciback 0000:01:00.0: AMD_POLARIS10: performing pre-reset
pciback 0000:01:00.0: AMD_POLARIS10: performing reset
pciback 0000:01:00.0: AMD_POLARIS10: CLOCK_CNTL: 0x0, PC: 0x2a2c
pciback 0000:01:00.0: AMD_POLARIS10: performing post-reset
pciback 0000:01:00.0: AMD_POLARIS10: reset result = 0
```

Host details:
- uefi system
- Xcp-NG 8.2
- enabled integrated graphic from bios
- used `xen-pciback.hide` to "hide" RX570

VM details:
- uefi system
- passed through the graphic card
- Windows 10 pro (upgraded to 20H2 update)
- freshly installed
- tried both AMD official drivers and Windows ones

If I missed something, or you need any further info, just tell me.

**Comment by gnif** [comment] 2020-12-01 11:41
Duplicate of #4

**Closed by gnif** 2020-12-01 11:41 UTC
