### ISSUE TITLE
modinfo missing version number of module -> DKMS will not update the module?

### ISSUE THREAD

**Issue by netinetwalker** [gnif/vendor-reset#19] opened 2021-01-16 13:15 UTC
modinfo missing version number of module -> DKMS will not update the module because of it?

dkms on debian dont replace the module with a new one. 

dkms status “WARNING! Diff between built and installed module”

```
#modinfo vendor-reset

filename:       /lib/modules/5.4.78-2-pve/updates/dkms/vendor-reset.ko
author:         Adam Madsen <adam@ajmadsen.com>
author:         Geoffrey McRae <geoff@hostfission.com>
license:        GPL v2
srcversion:     533BB7E5866E52F63B9ACCB
depends:        
retpoline:      Y
name:           vendor_reset
vermagic:       5.4.78-2-pve SMP mod_unload modversions 
parm:           install_hook:bool
```

**Comment by gnif** [comment] 2021-01-16 15:53
Please read up on how to properly use DKMS, not a bug, closing as invalid

**Closed by gnif** 2021-01-16 15:53 UTC

**Comment by netinetwalker** [comment] 2021-01-16 19:31
@gnif ok not a bug but a feature request ... ;-P

In the module the Version number is missing. MODULE_VERSION is not set!
dkms use this information to replace the module if nessesarry. In my case it does not update the vendor-reset.ko 0.0.18 with the new 0.0.19 (audio reset branch).
